### ISSUE TITLE
Update to OSQP 0.4.1

### ISSUE THREAD

**Issue by bstellato** [oxfordcontrol/osqp.rs#6] opened 2018-10-15 14:00 UTC
Just keeping track of it. Version 0.4.1 improves some minor things that we should include in Rust.

**Comment by ebarnard** [comment] 2018-10-15 23:03
This is not quite so simple as `osqp_setup` can now error if the problem is non-convex but this library has assumed (incorrectly) that `osqp_setup` only returns `NULL` on memory allocation failure - some settings validity is checked on assignment and data validity is checked in this library as otherwise it can lead to some nasty memory safety bugs.

Probably for the moment the answer is document and fix in the 0.5 release (next breaking change version).

**Comment by ebarnard** [comment] 2018-10-15 23:06
See oxfordcontrol/osqp#100.

**Closed** 2018-10-17 13:01 UTC
